//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingdongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMENTS()
        {
            this.COMMENT_FEEDBACK = new HashSet<COMMENT_FEEDBACK>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<decimal> BOOK_ID { get; set; }
        public string TITLE { get; set; }
        public string CONTENT { get; set; }
        public string TIME { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string TOTAL_LIKE { get; set; }
        public string TOTAL_DISLIKE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENT_FEEDBACK> COMMENT_FEEDBACK { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
