//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingdongBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.ORDER_INCLUDE = new HashSet<ORDER_INCLUDE>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> USER_ID { get; set; }
        public Nullable<decimal> ADDRESS_ID { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string REMARK { get; set; }
        public string TIME_START { get; set; }
        public string TIME_GET { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> POST_COST { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_INCLUDE> ORDER_INCLUDE { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
